[project]
name = "cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "babel>=2.17.0",
    "cssmin>=0.2.0",
    "jinja2>=3.1.6",
    "markdown>=3.8",
]
